apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-chart.fullname" . }}
  namespace: devops-ns
spec:
  selector:
    app: devops
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000
