apiVersion: v1
kind: Service
metadata:
  name: devops
  namespace: devops-ns
spec:
  selector:
    app: devops
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
